## Append samples of your project ##
resources:
- federation-ai.open-cluster-management.io_v1alpha1_federatedlearning.yaml
- federation-ai.open-cluster-management.io_v1alpha1_federatedlearning_flock.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
