apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: {{.ManifestName}}
  namespace: {{.ManifestNamespace}}
spec:
  manifestConfigs:
    - resourceIdentifier:
        group: batch
        resource: jobs
        namespace: {{ .ClientJobNamespace }}
        name: {{ .ClientJobName }}
      updateStrategy:
        type: ServerSideApply
  deleteOption:
    propagationPolicy: SelectivelyOrphan
    selectivelyOrphans:
      orphaningRules:
      - group: ""
        resource: namespaces
        name: {{ .ClientJobNamespace }}
  workload:
    manifests:
      - kind: Namespace
        apiVersion: v1
        metadata:
          name: {{.ClientJobNamespace}}
      - kind: Job
        apiVersion: batch/v1
        metadata:
          name: {{ .ClientJobName }}
          namespace: {{ .ClientJobNamespace }}
        spec:
          selector:
            matchLabels:
              job-name: {{ .ClientJobName }}
          template:
            metadata:
              labels:
                job-name: {{ .ClientJobName }}
            spec:
              volumes:
                - name: client-data
                  hostPath:
                    path: {{ .DataPath }}
                    type: DirectoryOrCreate
              containers:
              - name: flock-alliance-client
                image: {{ .ClientJobImage }}
                imagePullPolicy: Always
                command:
                  - "python"
                  - "-u"
                  - "main.py"
                  - "--config"
                  - "config/conf.yaml"
                  - "--env-file"
                  - "/data/.env"
                  - "--override"
                  - "runtime.mode={{ .RuntimeMode }}"
                  - "--override"
                  - "runtime.gpu={{ .UseGPU }}"
                  {{- if .BlockchainRPC }}
                  - "--override"
                  - "blockchain.rpc={{ .BlockchainRPC }}"
                  {{- end }}
                  {{- if .TokenAddress }}
                  - "--override"
                  - "blockchain.token_address={{ .TokenAddress }}"
                  {{- end }}
                  {{- if .TaskAddress }}
                  - "--override"
                  - "blockchain.task_address={{ .TaskAddress }}"
                  {{- end }}
                  - "--override"
                  - "blockchain.stake={{ .Stake }}"
                  - "--override"
                  - "storage.backend={{ .StorageBackend }}"
                  - "--override"
                  - "storage.local.shared_dir={{ .LocalSharedDir }}"
                  - "--override"
                  - "training.no_incentive={{ .NoIncentive }}"
                  - "--override"
                  - "training.num_participants={{ .NumParticipants }}"
                  - "--override"
                  - "data.inputs=/data"
                env:
                  - name: PRIVATE_KEY
                    valueFrom:
                      secretKeyRef:
                        name: {{ .PrivateKeySecretName }}
                        key: {{ .PrivateKeySecretKey }}
                  {{- if .HasHFTokenSecret }}
                  - name: HF_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: {{ .HFTokenSecretName }}
                        key: {{ .HFTokenSecretKey }}
                        optional: true
                  {{- end }}
                volumeMounts:
                  - name: client-data
                    mountPath: /data
              restartPolicy: Never
